apiVersion: v1
kind: Service
metadata:
  labels:
    app: booking
  name: booking
  namespace: kanwalnainsingh
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: booking
  type: ClusterIP
